/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.5
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.swagger.petstore.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 * @param code
 * @param type
 * @param message
 */

data class ApiResponse(
    @field:JsonProperty("code")
    val code: kotlin.Int? = null,
    @field:JsonProperty("type")
    val type: kotlin.String? = null,
    @field:JsonProperty("message")
    val message: kotlin.String? = null
)

