/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.5
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.swagger.petstore.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 * @param id
 * @param username
 * @param firstName
 * @param lastName
 * @param email
 * @param password
 * @param phone
 * @param userStatus User Status
 */

data class User(
    @field:JsonProperty("id")
    val id: kotlin.Long? = null,
    @field:JsonProperty("username")
    val username: kotlin.String? = null,
    @field:JsonProperty("firstName")
    val firstName: kotlin.String? = null,
    @field:JsonProperty("lastName")
    val lastName: kotlin.String? = null,
    @field:JsonProperty("email")
    val email: kotlin.String? = null,
    @field:JsonProperty("password")
    val password: kotlin.String? = null,
    @field:JsonProperty("phone")
    val phone: kotlin.String? = null,
    /* User Status */
    @field:JsonProperty("userStatus")
    val userStatus: kotlin.Int? = null
)

